### ISSUE TITLE
Changes on core interface to be less error prone

### ISSUE THREAD

**Issue by ajiyakin** [AccelByte/eventstream-go-sdk#12]
Currently the interface for this SDK is
```
err := client.Register(
		NewSubscribe().
			Topic(topicName).
			EventName(mockEvent.EventName).
			GroupID(groupID).
			Context(Context).
			Callback(func(event *Event, err error) {}))
```
which I think is pretty error prone, like forget to call `.Topic` or `.EventName` or else. So what I propose is to change it to something like this one
```
err := client.Register(NewSubscriber(topicName, eventName, groupID, context, callbackFunc))
```
this way, the user will be forced to fill-in those required params in order to correctly register the subscriber.

Although, I know that changing core interface will cause the user of this SDK to update the implementation, but I think on long run, it is worth to change. The semver will also be helpful for transitioning to this new interface.

cc @anggorodewanto @fadhillahentino @thoriqsatriya @desnia

**Comment by fadhillahentino** [comment]
We can get the error if the required params aren't fill-in but we will know that error after the service is running and thats not good enaough because we cant catch the error earlier.
Actually, we want to have same feeling with go-restful implementation (api.go) so we choose to use builder pattern in here
So, I will noted your concern and will race this issue to Justice team or if we have spare time in VE, we will trying to find best way for this. thanks

**Comment by IAD** [comment]
@ajiyakin @fadhillahentino currently we use stronger validation https://github.com/AccelByte/eventstream-go-sdk/blob/master/validation.go#L40
this prevents silent quits and we expect that this will be catched by tests

**Comment by ajiyakin** [comment]
Cool. That's better :+1:
